import { Inter } from "next/font/google";
import { FaMoon } from "react-icons/fa";
import { BsCart3 } from "react-icons/bs";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="header-top">
            <div className="container">
              <div className="auth">
              <a href="#">Sign Up</a>
              <a href="#">Create Account</a>
              </div>
            </div>
          </div>
        <div className="header-bottom">
          <div className="container">
            <div className="header-logo">
             <div className="logo">
             <h1>C</h1>
             </div>
              <nav>
                  <a href="/">home</a>
                  <a href="/about">about</a>
                  <a href="/products">products</a>
                  <a href="/contact">contact</a>
              </nav>
              <div className="cart">
              <FaMoon />
              <BsCart3 />
              </div>
            </div>
          </div>
        </div>
        </header>
        {children}
        </body>
    </html>
  );
}
